//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.41208.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace ChineseLunarCalendarCS {
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ((resourceMan == null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChineseLunarCalendarCS.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast Error!.
        /// </summary>
        internal static string CastError {
            get {
                return ResourceManager.GetString("CastError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jia,Yi,Bing,Ding,Wu,Ji,Geng,Xin,Ren,Gui.
        /// </summary>
        internal static string CelestialStem {
            get {
                return ResourceManager.GetString("CelestialStem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rat,Ox,Tiger,Rabbit,Dragon,Snake,Horse,Ram,Monkey,Rooster,Dog,Pig.
        /// </summary>
        internal static string ChineseZodiac {
            get {
                return ResourceManager.GetString("ChineseZodiac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected date.
        /// </summary>
        internal static string ExceptionName {
            get {
                return ResourceManager.GetString("ExceptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date!Current calendar only supports date from 2000-1-1 to 2020-12-31,please reselect!.
        /// </summary>
        internal static string OutOfRangeException {
            get {
                return ResourceManager.GetString("OutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slight Cold,Great Cold,Spring Begins,Rain Water,Excited Insects,Spring Equinox,Pure Brightness,Grain Rain,Summer Begins,Gain Full,Gain in Ear,Summer Solstice,Slight Heat,Great Heat,Autumn Begins,Limit of Heat,White Dew,Autumnal Equinox,Code Dew,Frost’s Descent,Winter Begins,Slight Snow,Great Snow,Winter Solstice.
        /// </summary>
        internal static string SolarTerms {
            get {
                return ResourceManager.GetString("SolarTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zi,Chou,Yin,Mao,Chen,Si,Wu,Wei,Shen,You,Xu,Hai.
        /// </summary>
        internal static string TerrestrialBranch {
            get {
                return ResourceManager.GetString("TerrestrialBranch", resourceCulture);
            }
        }
    }
}
